package com.codelib.springboot.sample.springsecurity.mapper;

import com.codelib.springboot.sample.springsecurity.pojo.GroupMemberExample;
import com.codelib.springboot.sample.springsecurity.pojo.GroupMemberKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    long countByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int deleteByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GroupMemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int insert(GroupMemberKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int insertSelective(GroupMemberKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    List<GroupMemberKey> selectByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupMemberKey record, @Param("example") GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupMemberKey record, @Param("example") GroupMemberExample example);
}