package com.codelib.springboot.sample.mybatis.mapper;

import com.codelib.springboot.sample.mybatis.pojo.StudentCourseExample;
import com.codelib.springboot.sample.mybatis.pojo.StudentCourseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    long countByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int deleteByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(StudentCourseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int insert(StudentCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int insertSelective(StudentCourseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    List<StudentCourseKey> selectByExample(StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StudentCourseKey record, @Param("example") StudentCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_courses
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StudentCourseKey record, @Param("example") StudentCourseExample example);
}