package com.codelib.springboot.sample.mybatis.mapper;

import com.codelib.springboot.sample.mybatis.pojo.Textbook;
import com.codelib.springboot.sample.mybatis.pojo.TextbookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TextbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    long countByExample(TextbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int deleteByExample(TextbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int insert(Textbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int insertSelective(Textbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    List<Textbook> selectByExample(TextbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    Textbook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Textbook record, @Param("example") TextbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Textbook record, @Param("example") TextbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Textbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbooks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Textbook record);
}