package com.codelib.springsecurity.sample.web.mapper;

import com.codelib.springsecurity.sample.web.pojo.GroupAuthorityExample;
import com.codelib.springsecurity.sample.web.pojo.GroupAuthorityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    long countByExample(GroupAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int deleteByExample(GroupAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GroupAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int insert(GroupAuthorityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int insertSelective(GroupAuthorityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    List<GroupAuthorityKey> selectByExample(GroupAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupAuthorityKey record, @Param("example") GroupAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupAuthorityKey record, @Param("example") GroupAuthorityExample example);
}